version: "3.9"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: naijacost-servercon
    environment:
      - PORT=8080
  database:
    image: postgres:latest
    container_name: naijacost-dbcon
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: efosa
      POSTGRES_PASSWORD: password
      POSTGRES_DB: naijacost_db
    # volumes:
    #   - db_data:/var/lib/postgresql/data
