// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type StatesCost struct {
	State          string        `json:"state"`
	AirCost        pgtype.Float8 `json:"air_cost"`
	BusCostInter   pgtype.Float8 `json:"bus_cost_inter"`
	BusCostIntra   pgtype.Float8 `json:"bus_cost_intra"`
	MotorcycleCost pgtype.Float8 `json:"motorcycle_cost"`
	WaterCost      pgtype.Float8 `json:"water_cost"`
}
