// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type StatesCost struct {
	State          string
	AirCost        pgtype.Float8
	BusCostInter   pgtype.Float8
	BusCostIntra   pgtype.Float8
	MotorcycleCost pgtype.Float8
	WaterCost      pgtype.Float8
}
