// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: states_transport_cost.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type BulkInsertStateTransportCostsParams struct {
	State          string        `json:"state"`
	AirCost        pgtype.Float8 `json:"air_cost"`
	BusCostInter   pgtype.Float8 `json:"bus_cost_inter"`
	BusCostIntra   pgtype.Float8 `json:"bus_cost_intra"`
	MotorcycleCost pgtype.Float8 `json:"motorcycle_cost"`
	WaterCost      pgtype.Float8 `json:"water_cost"`
}

const getStateCost = `-- name: GetStateCost :one
SELECT state, air_cost, bus_cost_inter, bus_cost_intra, motorcycle_cost, water_cost FROM states_transport_cost
WHERE State = $1
`

func (q *Queries) GetStateCost(ctx context.Context, state string) (StatesTransportCost, error) {
	row := q.db.QueryRow(ctx, getStateCost, state)
	var i StatesTransportCost
	err := row.Scan(
		&i.State,
		&i.AirCost,
		&i.BusCostInter,
		&i.BusCostIntra,
		&i.MotorcycleCost,
		&i.WaterCost,
	)
	return i, err
}

const listStatesCosts = `-- name: ListStatesCosts :many
SELECT state, air_cost, bus_cost_inter, bus_cost_intra, motorcycle_cost, water_cost FROM states_transport_cost
ORDER BY State
`

func (q *Queries) ListStatesCosts(ctx context.Context) ([]StatesTransportCost, error) {
	rows, err := q.db.Query(ctx, listStatesCosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StatesTransportCost
	for rows.Next() {
		var i StatesTransportCost
		if err := rows.Scan(
			&i.State,
			&i.AirCost,
			&i.BusCostInter,
			&i.BusCostIntra,
			&i.MotorcycleCost,
			&i.WaterCost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
