// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: states_food_costs.sql

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type BulkInsertStateFoodCostsParams struct {
	State string        `json:"state"`
	Cost  pgtype.Float8 `json:"cost"`
}
